/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("WarehousesObjectPageObjectPage journey");

        opaTest("Navigate to WarehousesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheWarehousesListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheWarehousesListGenerated.onTable().iCheckRows();
            When.onTheWarehousesListGenerated.onTable().iPressRow(0);

            Then.onTheWarehousesObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheWarehousesObjectPageGenerated.iCheckNumberOfSections(3);
        });

        opaTest("Check the WarehouseKPIFacet section of the Object Page", function (_Given, When, Then) {
            When.onTheWarehousesObjectPageGenerated.iGoToSection({ section: "WarehouseKPIFacet" });
            Then.onTheWarehousesObjectPageGenerated.iCheckSection({ section: "WarehouseKPIFacet" });
            Then.onTheWarehousesObjectPageGenerated.onForm({ section: "WarehouseKPIFacet" }).iCheckField({ property: "totalMaterials" });
            Then.onTheWarehousesObjectPageGenerated.onForm({ section: "WarehouseKPIFacet" }).iCheckField({ property: "lowStockCount" });
            Then.onTheWarehousesObjectPageGenerated.onForm({ section: "WarehouseKPIFacet" }).iCheckField({ property: "criticalCount" });
            Then.onTheWarehousesObjectPageGenerated.onForm({ section: "WarehouseKPIFacet" }).iCheckField({ property: "stockValue" });
        });

        opaTest("Check the WarehouseInfoFacet section of the Object Page", function (_Given, When, Then) {
            When.onTheWarehousesObjectPageGenerated.iGoToSection({ section: "WarehouseInfoFacet" });
            Then.onTheWarehousesObjectPageGenerated.iCheckSection({ section: "WarehouseInfoFacet" });
            Then.onTheWarehousesObjectPageGenerated.onForm({ section: "WarehouseInfoFacet" }).iCheckField({ property: "name" });
            Then.onTheWarehousesObjectPageGenerated.onForm({ section: "WarehouseInfoFacet" }).iCheckField({ property: "code" });
            Then.onTheWarehousesObjectPageGenerated.onForm({ section: "WarehouseInfoFacet" }).iCheckField({ property: "location" });
        });

        opaTest("Check the InventoryFacet section of the Object Page", function (_Given, When, Then) {
            When.onTheWarehousesObjectPageGenerated.iGoToSection({ section: "InventoryFacet" });
            Then.onTheWarehousesObjectPageGenerated.iCheckSection({ section: "InventoryFacet" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});