/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaterialsObjectPageObjectPage journey");

        opaTest("Navigate to MaterialsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheMaterialsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheMaterialsListGenerated.onTable().iCheckRows();
            When.onTheMaterialsListGenerated.onTable().iPressRow(0);

            Then.onTheMaterialsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheMaterialsObjectPageGenerated.iCheckNumberOfSections(2);
        });

        opaTest("Check the MaterialInfoFacet section of the Object Page", function (_Given, When, Then) {
            When.onTheMaterialsObjectPageGenerated.iGoToSection({ section: "MaterialInfoFacet" });
            Then.onTheMaterialsObjectPageGenerated.iCheckSection({ section: "MaterialInfoFacet" });
            Then.onTheMaterialsObjectPageGenerated.onForm({ section: "MaterialInfoFacet" }).iCheckField({ property: "code" });
            Then.onTheMaterialsObjectPageGenerated.onForm({ section: "MaterialInfoFacet" }).iCheckField({ property: "name" });
            Then.onTheMaterialsObjectPageGenerated.onForm({ section: "MaterialInfoFacet" }).iCheckField({ property: "unit" });
            Then.onTheMaterialsObjectPageGenerated.onForm({ section: "MaterialInfoFacet" }).iCheckField({ property: "unitCost" });
            Then.onTheMaterialsObjectPageGenerated.onForm({ section: "MaterialInfoFacet" }).iCheckField({ property: "status" });
        });

        opaTest("Check the StockByWarehouseFacet section of the Object Page", function (_Given, When, Then) {
            When.onTheMaterialsObjectPageGenerated.iGoToSection({ section: "StockByWarehouseFacet" });
            Then.onTheMaterialsObjectPageGenerated.iCheckSection({ section: "StockByWarehouseFacet" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});